services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=petsDB'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1234'
    ports:
      - '5432'
    container_name: 'pg'
    volumes:
      - .:/docker-entrypoint-initdb.d

  app:
    build: ./
    container_name: 'app'
    ports:
      - 8080:8080
